export const COUNT_LIST_REQUEST ='COUNT_LIST_REQUEST'
export const COUNT_LIST_SUCCESS ='COUNT_LIST_SUCCESS'
export const COUNT_LIST_FAIL ='COUNT_LIST_FAIL'

export const GET_BOOKING_LIST_REQUEST ='GET_BOOKING_LIST_REQUEST'
export const GET_BOOKING_LIST_SUCCESS ='GET_BOOKING_LIST_SUCCESS'
export const GET_BOOKING_LIST_FAIL ='GET_BOOKING_LIST_FAIL'

export const APPROVE_BOOKING_REQUEST ='APPROVE_BOOKING_REQUEST'
export const APPROVE_BOOKING_SUCCESS ='APPROVE_BOOKING_SUCCESS'
export const APPROVE_BOOKING_FAIL ='APPROVE_BOOKING_FAIL'
export const APPROVE_BOOKING_RESET ='APPROVE_BOOKING_RESET'

export const REJECT_BOOKING_REQUEST ='REJECT_BOOKING_REQUEST'
export const REJECT_BOOKING_SUCCESS ='REJECT_BOOKING_SUCCESS'
export const REJECT_BOOKING_FAIL ='REJECT_BOOKING_FAIL'
export const REJECT_BOOKING_RESET ='REJECT_BOOKING_RESET'