export const PROPERTIES_LIST_REQUEST ='PROPERTIES_LIST_REQUEST'
export const PROPERTIES_LIST_SUCCESS ='PROPERTIES_LIST_SUCCESS'
export const PROPERTIES_LIST_FAIL ='PROPERTIES_LIST_FAIL'

export const ADD_PROPERTIES_REQUEST ='ADD_PROPERTIES_REQUEST'
export const ADD_PROPERTIES_SUCCESS ='ADD_PROPERTIES_SUCCESS'
export const ADD_PROPERTIES_FAIL ='ADD_PROPERTIES_FAIL'
export const ADD_PROPERTIES_RESET='ADD_PROPERTIES_RESET'

export const DELETE_PROPERTIES_REQUEST ='DELETE_PROPERTIES_REQUEST'
export const DELETE_PROPERTIES_SUCCESS ='DELETE_PROPERTIES_SUCCESS'
export const DELETE_PROPERTIES_FAIL ='DELETE_PROPERTIES_FAIL'
export const DELETE_PROPERTIES_RESET ='DELETE_PROPERTIES_RESET'

export const PROPERTIES_DETAILS_REQUEST ='PROPERTIES_DETAILS_REQUEST'
export const PROPERTIES_DETAILS_SUCCESS ='PROPERTIES_DETAILS_SUCCESS'
export const PROPERTIES_DETAILS_FAIL ='PROPERTIES_DETAILS_FAIL'
export const PROPERTIES_DETAILS_RESET ='PROPERTIES_DETAILS_RESET'


export const UPDATE_PROPERTIES_REQUEST ='UPDATE_PROPERTIES_REQUEST'
export const UPDATE_PROPERTIES_SUCCESS ='UPDATE_PROPERTIES_SUCCESS'
export const UPDATE_PROPERTIES_FAIL ='UPDATE_PROPERTIES_FAIL'
export const UPDATE_PROPERTIES_RESET ='UPDATE_PROPERTIES_RESET'
